version: '3'

services:
  service-blog:
   build: ./servicos
   volumes:
     - ./servicos:/usr/src/app
   ports:
     - 5001:80
  service-login:
    build: ./sistemaLogin
    volumes:
      - ./sistemaLogin:/usr/src/login
    ports:
      - 5002:80
